apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bb-01
              image: busybox:1.36
              command: [/bin/sh, -c, "date; sleep 15"]
          restartPolicy: OnFailure