apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: local-storage
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/storage1