apiVersion: v1
kind: Pod
metadata:
  name: test-01
spec:
  containers:
    - name: test
      image: busybox:1.36
      command: ["sh", "-c", "echo qwerty && sleep 3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "300m"
      livenessProbe:
        exec:
          command: [ "echo", "testing" ]
        initialDelaySeconds: 5
        periodSeconds: 5