apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test-01
spec:
  containers:
    - name: test1
      args:
        - /bin/sh
        - -c
        - while true; do date >> /tmp/date/log; sleep 5; done
      image: busybox:1.36
      volumeMounts:
        - name: vol1
          mountPath: /tmp/date
    - name: test2
      args: [/bin/sh, -c, "while true; do wc -l /tmp/anotherMount/log; sleep 1; done"]
      image: busybox:1.36
      volumeMounts:
        - name: vol1
          mountPath: /tmp/anotherMount
          readOnly: true
  volumes:
    - name: vol1
      emptyDir: {}

