apiVersion: v1
kind: Pod
metadata:
  name: test-01
  labels:
    app: test
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ['sh', '-c', 'echo "Hello Marek!" && sleep 3600']